
name = "hello-sunshine"
compatibility_date = "2026-06-27"
main = "worker.ts"

[observability]
enabled = true

[site]
bucket = "artifacts/hello-sunshine/dist/public"

compatibility_flags = ["nodejs_compat"]
