name = "hello-sunshine"
compatibility_date = "2026-06-27"
main = "worker.ts"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[site]
bucket = "artifacts/hello-sunshine/dist/public"

# [build]
# command = "pnpm run build"
